name: Build and Test

on:
  pull_request_target:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Build and Test
        run: |
          dotnet test --configuration Release --filter *.Tests
          dotnet publish --configuration Release --output ./publish

      - name: Copy project files to staging directory
        run: |
          mkdir -p ${{ github.workspace }}/artifacts
          cp -R ./publish/. ${{ github.workspace }}/artifacts

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: project
          path: ${{ github.workspace }}/artifacts

  